# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e13dfaf602aef45ba3528c185f69584"
name = "all-right-solutions-dev"
application_url = "https://allright-solutions.online"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_metaobject_definitions,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [
  "https://allright-solutions.online/auth/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
